version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: phpfullstacktest/backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: phpfullstacktest/phpfullstacktest_db
    container_name: phpfullstacktest_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: php_fullstack_test
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

react:
    image: phpfullstacktest/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - laravel
    command: npm run dev


volumes:
  dbdata:

networks:
  laravel:
